name: "Evolan"
description: "个人主页 / 技术博客 / 学习与项目记录"

avatar: https://evolan17.github.io/images/avatar.jpg
favicon: https://evolan17.github.io/images/avatar.jpg

navigation:
  - name: 首页
    url: /
  - name: 关于
    url: /about
  - name: 标签
    url: /tags

paginate: 8

excerpt_separator: <!-- more -->

footer-links:
  zhihu:
  email: jinmeihe280@gmail.com
  facebook:
  github: Evolan
  rss: welcome!
  twitter:
  youtube:

footer-text: Copyright (c) 2026 Evolan

url: https://evolan17.github.io

permalink: /:title/
paginate_path: /page:num/

# # Gitalk
# gitalk:
#   clientID: your_client_id
#   clientSecret: your_client_secret
#   repo: evolan17.github.io
#   owner: evolan

version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"

sass:
  style: :expanded

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
